server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-auth
    username: admin
    password: admin
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
    open-in-view: true