server:
  port: 8087
  servlet:
    context-path: '/ead-auth/'

spring:
  application:
    name: ead-auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-auth
    username: admin
    password: admin
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
    open-in-view: true
  output:
    ansi:
      enabled: always

# TRACE, DEGUG, INFO, WARN, ERROR
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    br.com.ead: DEBUG

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

ead:
  api:
    url:
      cursos: 'http://ead-curso-service/ead-cursos'
