server:
  port: ${PORT}
  servlet:
    context-path: '/ead-auth/'

spring:
  application:
    name: ead-auth-service

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
    open-in-view: true

  rabbitmq:
    addresses: ${CLOUDAMQP_URL}

# TRACE, DEGUG, INFO, WARN, ERROR
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    br.com.ead: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      circuitBreakerInstance:
        slidingWindowSize: 30
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30s
        failureRateThreshold: 80

  retry:
    instances:
      retryInstance:
        maxRetryAttemps: 3
        waitDuration: 5s

ead:
  api:
    url:
      cursos: 'http://ead-curso-service/ead-cursos'
  broker:
    exchange:
      usuarioEvent: ead.usuarioevent

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health