server:
  port: 8084
  servlet:
    context-path: '/ead-notificacoes/'

spring:
  application:
    name: ead-notificacao-service

  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-notificacao
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: '/'

  output:
    ansi:
      enabled: always

# TRACE, DEGUG, INFO, WARN, ERROR
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    br.com.ead: DEBUG

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

ead:
  broker:
    exchange:
      notificacaoCommandExchange: ead.notificacaocommand
    queue:
      notificacaoCommandQueue:
        name: ead.notificacaocommand.ms.notificacao
    key:
      notificacaoCommandKey: ms.notificacao