server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      routes:
        - id: ead-auth-service
          uri: lb://EAD-AUTH-SERVICE
          predicates:
            - Path=/ead-auth/**
        - id: ead-curso-service
          uri: lb://EAD-CURSO-SERVICE
          predicates:
            - Path=/ead-cursos/**

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost